#!/usr/bin/env python3
"""
test_redact.py — redaction proof (the instructor's "before/after" requirement,
as a reproducible test rather than a screenshot).

It plants fake secrets into a realistic alert, asserts that NONE of them survive
into the redacted object that would be sent to the LLM, and writes a human-readable
before/after proof to outputs/redaction_proof.md.

Run:  python tests/test_redact.py      (exits non-zero if any secret leaks)
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from redact import redact_alert, redact_text, find_secrets  # noqa: E402

# A realistic alert with fake secrets deliberately planted in several places.
PLANTED = {
    "alert_id": "TEST-SECRET-01",
    "rule_id": "100201",
    "rule_description": "Encoded PowerShell executed",
    "agent": "win-victim",
    "password": "Sup3rSecret!",                       # sensitive KEY -> whole value dropped
    "key_fields": {
        "CommandLine": ("powershell -c \"$c = 'password=Hunter2'; "
                        "Invoke-RestMethod -Headers @{Authorization='Bearer eyJhbGciOiJIUzI1NiJ9.abc.def'}\""),
        "env": "AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEYAB",
        "api_key": "sk-abcdEFGH1234567890ijklmnopQRST",
        "note": "user pasted -----BEGIN OPENSSH PRIVATE KEY-----AAAAB3Nz...tail-----END OPENSSH PRIVATE KEY-----",
    },
    "Hashes": "SHA256=65EC268ADD3973B6DCA64222985DA47CAEAEE44A340B0EC1466782914FD743D9",  # IOC, kept
}

# The literal secret values that must NOT appear anywhere in the redacted output.
LEAKS = ["Sup3rSecret!", "Hunter2", "eyJhbGciOiJIUzI1NiJ9.abc.def",
         "AKIAIOSFODNN7EXAMPLE", "wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEYAB",
         "sk-abcdEFGH1234567890ijklmnopQRST", "AAAAB3Nz"]


def main():
    redacted = redact_alert(PLANTED)
    blob = json.dumps(redacted)

    leaked = [s for s in LEAKS if s in blob]
    hash_kept = "65EC268ADD3973B6DCA64222985DA47CAEAEE44A340B0EC1466782914FD743D9" in blob

    # write the before/after proof
    outdir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "outputs")
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "redaction_proof.md"), "w", encoding="utf-8") as f:
        f.write("# Redaction proof — AlertMind assistant\n\n")
        f.write("Generated by `tests/test_redact.py`. Fake secrets are planted in an alert, "
                "then `redact_alert()` is applied BEFORE any prompt is built. None of the "
                "planted secret values survive; the file hash (an IOC) is preserved.\n\n")
        f.write(f"**Result:** {'PASS — no secret leaked' if not leaked else 'FAIL — leaked: ' + str(leaked)} · "
                f"file-hash IOC preserved: {hash_kept}\n\n")
        f.write("## BEFORE (raw alert with planted secrets)\n\n```json\n")
        f.write(json.dumps(PLANTED, indent=2))
        f.write("\n```\n\n## AFTER (redacted — this is what the LLM would receive)\n\n```json\n")
        f.write(json.dumps(redacted, indent=2))
        f.write("\n```\n\n## Planted secrets and whether each was removed\n\n")
        f.write("| Secret (fake) | Removed |\n|---|---|\n")
        for s in LEAKS:
            f.write(f"| `{s[:40]}` | {'✅' if s not in blob else '❌ LEAKED'} |\n")

    print("redacted object the LLM would receive:")
    print(json.dumps(redacted, indent=2))
    print()
    if leaked:
        print("FAIL — these secrets leaked:", leaked)
        return 1
    if not hash_kept:
        print("WARN — file-hash IOC was stripped (should be kept)")
    print(f"PASS — 0/{len(LEAKS)} secrets leaked; file-hash IOC preserved={hash_kept}")
    print("proof written to outputs/redaction_proof.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
